CREATE DATABASE Portfolio;
SHOW DATABASES;
CREATE TABLE Contact_form (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Subject VARCHAR(255),
    Message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

